name: Backend CI/CD

on:
  pull_request:
    branches:
      - main
      - dev
    paths:
      - backend/**
      - .github/** # Github Actions 작업을 위한 포함
  push:
    branches:
      - main
      - dev
    paths:
      - backend/**
      - .github/** # Github Actions 작업을 위한 포함

jobs:
  build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"

      # - name: Grant execute permission for gradlew
      #   run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: pass JAR file through SCP
        uses: appleboy/scp-action@master
        with:
          username: ubuntu
          host: ${{ secrets.HOST }}
          key: ${{ secrets.PASSWORD }}
          source: "./build/libs/*.jar"
          target: "/home/ubuntu/diabetes/backend/"

      # - name: Execute Server Init Script
      #   uses: appleboy/ssh-action@master
      #   with:
      #     username: ubuntu
      #     host: ${{ secrets.HOST }}
      #     key: ${{ secrets.PASSWORD }}
      #     script_stop: true
      #     script: . /home/ubuntu/diabetes/backend/run.sh
