name: Backend CI/CD

on:
    push:
        branches:
            - main
            - dev
        paths:
            - backend/**
            - .github/workflows/back-end-ci-cd-test.yml # Github Actions 작업을 위한 포함

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./back_end

        steps:
            - uses: actions/checkout@v3

            - name: Set up JDK 11
              uses: actions/setup-java@v3
              with:
                  java-version: "11"
                  distribution: "temurin"

            - name: Grant execute permission for gradlew
              run: chmod +x gradlew

            - name: Build with Gradle
              run: ./gradlew build -x test

            - name: show pwd
              run: |
                  pwd
                  ls

            - name: pass JAR file through SCP
              uses: appleboy/scp-action@master
              env:
                  HOST: ${{ secrets.HOST }}
                  USERNAME: ${{ secrets.USERNAME }}
                  PORT: ${{ secrets.PORT }}
                  KEY: ${{ secrets.PASSWORD }}
              with:
                  source: "."
                  target: "/home/ubuntu/diabetes/back_end/build/"

            # - name: Execute Server Init Script
            #   uses: appleboy/ssh-action@master
            #   with:
            #     username: ubuntu
            #     host: ${{ secrets.HOST }}
            #     key: ${{ secrets.PASSWORD }}
            #     script_stop: true
            #     script: . /home/ubuntu/diabetes/backend/run.sh
