name: front-end-build
on:
    pull_request:
        branches:
            - main
            - dev
        paths:
            - front-end/**
            - .github/workflows/front-end-ci.yml
    push:
        branches:
            - main
            - dev
        paths:
            #- front-end/**
            - .github/**

jobs:
    build:
        name: frontend-build
        runs-on: ubuntu-latest
        # env:
        # working-directory: ./front-end

        defaults:
            run:
                working-directory: ./front-end

        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: npm install
              run: npm install

            - name: build
              run: npm run build

            - name: executing remote ssh commands using password
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.PASSWORD }}
                  port: ${{ secrets.PORT }}
                  script: |
                      rm -rf /home/ubuntu/diabetes/front-end/build/

            - name: show files
              run: |
                  ls
                  pwd
                  ls ./build

            - name: copy file via ssh password
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  port: ${{ secrets.PORT }}
                  key: ${{ secrets.PASSWORD }}
                  source: "build/*"
                  target: "/home/ubuntu/diabetes/front-end/"
