name: build
on:
  pull_request:
    branches:
      - main
      - dev
    paths:
      - front-end/**
      - .github/**
  push:
    branches:
      - main
      - dev
    paths:
      - front-end/**
      - .github/**


jobs:
  build:
    runs-on: ubuntu-20.04
    # env:
      # working-directory: ./front-end
      
    defaults:
      run:
        working-directory: ./front-end
        
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: npm install
        run: npm install
        
      - name: build
        run: npm run build
  
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            rm -rf /home/ubuntu/diabetes/front-end/build/

      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.0.1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: 'build'
          target: '/home/ubuntu/diabetes/front-end/'
